envs: local, staging, prod
routes:
  - root_route:
    - envs: staging, prod
    - path: "/abc"
    - component: "common/AbcComponent"
    - vars: 
      - config: a
  - root_route_local: 
    - envs: local
    - path: "/abc"
    - component: "common/AbcComponent"
    - vars: 
      - config: b
  - not_found:
    - envs: all
    - path: "*"
    - kind: fallback
    - component: "error/NotFoundComponent"
    - vars: 
      - config: a