version: '3'

vars:
  LOGS_ON: 'export MO_INT_LOGS=true && export MO_INT_LOGS_LEVEL=INFO'
  LOGS_OFF: 'export MO_INT_LOGS=false && export MO_INT_LOGS_LEVEL=INFO'

tasks:
  test:
    cmds:
      - 'export LIBRARY_PATH="" && export DYLD_LIBRARY_PATH="{{.ROOT_DIR}}/fragments/libs" && export MACOSX_DEPLOYMENT_TARGET=$(sw_vers -productVersion) && cd compiler && crystal spec --link-flags="-L{{.ROOT_DIR}}/fragments/libs"'

  init-test:
    cmds:
      - 'export MACOSX_DEPLOYMENT_TARGET=$(sw_vers -productVersion) && cd compiler && rm -rf ./motestproj &&  time crystal run src/mochi.cr -- --initialize="motestproj"'

  run:
    cmds:
      - 'export LIBRARY_PATH="" && export DYLD_LIBRARY_PATH="{{.ROOT_DIR}}/fragments/libs" && export MACOSX_DEPLOYMENT_TARGET=$(sw_vers -productVersion) && {{.LOGS_ON}} && cd compiler && time crystal run src/mochi.cr --link-flags="-L{{.ROOT_DIR}}/fragments/libs" -- -i "../devground/components" -o "../devground/public" --minimize'

  run-no-internal-logs:
    cmds:
      - 'export MACOSX_DEPLOYMENT_TARGET=$(sw_vers -productVersion) && {{.LOGS_OFF}} && cd compiler && time crystal run src/mochi.cr --link-flags="-L{{.ROOT_DIR}}/fragments/libs" -- -i "../devground/components" -o "../devground/public" --minimize'

  run-with-typecheck:
    cmds:
      - 'export MACOSX_DEPLOYMENT_TARGET=$(sw_vers -productVersion) && {{.LOGS_OFF}} && cd compiler && time crystal run src/mochi.cr --link-flags="-L{{.ROOT_DIR}}/fragments/libs" -- -i "../devground/components" -o "../devground/public" --minimize --typecheck'

  build:
    cmds:
      - 'export MACOSX_DEPLOYMENT_TARGET=$(sw_vers -productVersion) && cd compiler && time crystal build src/mochi.cr --link-flags="-L{{.ROOT_DIR}}/fragments/libs"'

  build-and-execute:
    deps:
      - build
    cmds:
      - 'export DYLD_LIBRARY_PATH="{{.ROOT_DIR}}/fragments/libs:$DYLD_LIBRARY_PATH" && {{.LOGS_ON}} && cd compiler && ./mochi -i "../devground/components" -o "../devground/public" --minimize --typecheck'

  dev:
    cmds:
      - 'export MACOSX_DEPLOYMENT_TARGET=$(sw_vers -productVersion) && cd compiler && crystal run src/mochi.cr --link-flags="-L{{.ROOT_DIR}}/fragments/libs" -- --dev --root="../devground/public"'

  e2e:
    deps:
      - run-tc
    cmds:
      - echo "-----------------------------------------------------------------------------------------------------"
      - 'export MO_INT_LOGS=true && cd e2e && npx playwright test'

  sorbet:
    cmds:
      - cd devground/components && srb tc

  generate-batteries:
    cmds:
      - ruby scripts/fragments_generator.rb
      - crystal tool format ./compiler/src/generated
