version: '3'

vars:
  FRAG_CONFIG:
    sh: |
      if [[ "$OSTYPE" == "darwin"* ]]; then
        echo 'export LIBRARY_PATH="" && export DYLD_LIBRARY_PATH="{{.ROOT_DIR}}/fragments/libs" && export MACOSX_DEPLOYMENT_TARGET=$(sw_vers -productVersion)'
      else
        echo 'export LIBRARY_PATH="" && export LD_LIBRARY_PATH="{{.ROOT_DIR}}/fragments/libs"'
      fi
  LINK_FLAGS: '--link-flags="-L{{.ROOT_DIR}}/fragments/libs"'
  DEFAULT_RUN_PARAMS: '-i "../devground/components" -o "../devground/public" --minimize'

tasks:
  specs:
    cmds:
      - '{{.FRAG_CONFIG}} && cd compiler && crystal spec {{.LINK_FLAGS}}'

  init-test:
    cmds:
      - '{{.FRAG_CONFIG}} && cd compiler && rm -rf ./motestproj &&  time crystal run src/mochi.cr {{.LINK_FLAGS}} -- --initialize="motestproj"'

  run:
    cmds:
      - '{{.FRAG_CONFIG}} && cd compiler && time crystal run src/mochi.cr {{.LINK_FLAGS}} -- {{.DEFAULT_RUN_PARAMS}}'

  run-no-internal-logs:
    cmds:
      - '{{.FRAG_CONFIG}} && cd compiler && time crystal run src/mochi.cr {{.LINK_FLAGS}} -- {{.DEFAULT_RUN_PARAMS}}'

  run-with-typecheck:
    cmds:
      - '{{.FRAG_CONFIG}} && cd compiler && time crystal run src/mochi.cr {{.LINK_FLAGS}} -- {{.DEFAULT_RUN_PARAMS}}'

  typecheck:
    cmds:
      - '{{.FRAG_CONFIG}} && cd compiler && time crystal run src/mochi.cr {{.LINK_FLAGS}} -- typecheck ../devground/components'

  build:
    cmds:
      - '{{.FRAG_CONFIG}} && cd compiler && time crystal build src/mochi.cr {{.LINK_FLAGS}}'

  build-and-execute:
    deps:
      - build
    cmds:
      - 'cd compiler && ./mochi {{.DEFAULT_RUN_PARAMS}}'

  dev:
    cmds:
      - '{{.FRAG_CONFIG}} && cd compiler && crystal run src/mochi.cr {{.LINK_FLAGS}} -- --dev --root="../devground/public"'

  e2e:
    deps:
      - run
    cmds:
      - echo "-----------------------------------------------------------------------------------------------------"
      - 'cd e2e && npx playwright test'

  sorbet:
    cmds:
      - cd devground/components && srb tc

  generate-batteries:
    cmds:
      - ruby scripts/fragments_generator.rb
      - crystal tool format ./compiler/src/generated
