version: '3'

tasks:
  test:
    cmds:
      - cd compiler && crystal spec
  intest:
    cmds:
      - cd compiler && rm -rf ./motestproj &&  time crystal run src/mochi.cr -- --initialize="motestproj"
  run:
    cmds:
      - export MO_INT_LOGS=true && export MO_INT_LOGS_LEVEL=INFO && cd compiler && time crystal run src/mochi.cr -- -i "../devground/components" -o "../devground/public" -m
  run-no-int-logs:
    cmds:
      - export MO_INT_LOGS=false && export MO_INT_LOGS_LEVEL=INFO && cd compiler && time crystal run src/mochi.cr -- -i "../devground/components" -o "../devground/public" -m
  run-tc:
    cmds:
      - export MO_INT_LOGS=false && export MO_INT_LOGS_LEVEL=INFO && cd compiler && time crystal run src/mochi.cr -- -i "../devground/components" -o "../devground/public" -m -tc
  build:
    cmds:
      - cd compiler && time crystal build src/mochi.cr
  dev:
    cmds:
      - cd compiler && crystal run src/mochi.cr -- --dev --root="../devground/public"
  e2e:
    deps:
      - run-tc
    cmds:
      - echo "-----------------------------------------------------------------------------------------------------"
      - export MO_INT_LOGS=true && cd e2e && npx playwright test
  ruby:
    cmds:
      - cd devground/components && ruby ./lib/Root.rb
  sorbet:
    cmds:
      - cd devground/components && srb tc
  dev-server:
    cmds:
      - crystal run testapp/test_app_server.cr
  generate-batteries:
    cmds:
      - ruby scripts/fragments_generator.rb
      - crystal tool format ./compiler/src/generated
