version: '3'

tasks:
  test:
    cmds:
      - cd crystal && crystal spec
  run:
    cmds:
      - cd crystal && time crystal run src/mochi.cr -- -i "../ruby/lib" -o "../devground" -m
  build:
    cmds:
      - cd crystal && time crystal build src/mochi.cr
