version: '3'

tasks:
  test:
    cmds:
      - cd crystal && crystal spec
  intest:
    cmds:
      - cd crystal && rm -rf ./motestproj &&  time crystal run src/mochi.cr -- --initialize="motestproj"
  run:
    cmds:
      - cd crystal && time crystal run src/mochi.cr -- -i "../ruby" -o "../devground" -m
  run-tc:
    cmds:
      - cd crystal && time crystal run src/mochi.cr -- -i "../ruby" -o "../devground" -m -tc
  build:
    cmds:
      - cd crystal && time crystal build src/mochi.cr
  e2e:
    deps:
      - run-tc
    cmds:
      - echo "-----------------------------------------------------------------------------------------------------"
      - cd e2e && npx playwright test
  ruby:
    cmds:
      - cd ruby && ruby ./lib/Root.rb
  sorbet:
    cmds:
      - cd ruby && srb tc
  dev-server:
    cmds:
      - cd testapp && npm run dev