version: '3'

tasks:
  test:
    cmds:
      - cd crystal && crystal spec
  intest:
    cmds:
      - cd crystal && rm -rf ./motestproj &&  time crystal run src/mochi.cr -- --initialize="motestproj"
  run:
    cmds:
      - export MO_INT_LOGS=true && export MO_INT_LOGS_LEVEL=INFO && cd crystal && time crystal run src/mochi.cr -- -i "../ruby" -o "../devground" -m
  run-no-int-logs:
    cmds:
      - export MO_INT_LOGS=false && export MO_INT_LOGS_LEVEL=INFO && cd crystal && time crystal run src/mochi.cr -- -i "../ruby" -o "../devground" -m
  run-tc:
    cmds:
      - export MO_INT_LOGS=false && export MO_INT_LOGS_LEVEL=INFO && cd crystal && time crystal run src/mochi.cr -- -i "../ruby" -o "../devground" -m -tc
  build:
    cmds:
      - cd crystal && time crystal build src/mochi.cr
  e2e:
    deps:
      - run-tc
    cmds:
      - echo "-----------------------------------------------------------------------------------------------------"
      - export MO_INT_LOGS=true && cd e2e && npx playwright test
  ruby:
    cmds:
      - cd ruby && ruby ./lib/Root.rb
  sorbet:
    cmds:
      - cd ruby && srb tc
  dev-server:
    cmds:
      - crystal run testapp/test_app_server.cr
  generate-batteries:
    cmds:
      - ruby scripts/fragments_generator.rb
      - crystal tool format ./crystal/src/generated
