version: '3'

tasks:
  dev:
    cmds:
      - ./gradlew shadowJar
      - java -jar build/libs/mochi.jar
      - #ruby generate_opal_runtime.rb
      - #cat devground/opal-runtime.js <(echo) devground/components.js > devground/bundle.js
      - #npx swc devground/bundle.js -o devground/bundle.min.js
  test:
    cmds:
      - cd crystal && crystal spec
  run:
    cmds:
      - cd crystal && time crystal run src/mochi.cr -- -i "../ruby/lib" -o "../devground" -m
  build:
    cmds:
      - cd crystal && time crystal build src/mochi.cr
    